name: "Create cluster using Minikube"
on: [pull_request, push]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
#     container:
#       image: node:14.16
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
    steps:
    - uses: actions/checkout@master
#     - uses: opsgang/ga-setup-minikube@v0.1.1
#       with:
#         minikube-version: 1.4.0
#         k8s-version: 1.15.1
    - name: Testing
      run: |
        uptime
        ps -ef
        docker images
        docker ps 
        
    - name: Testing2
      run: |
        ps -ef
        
    - name: Testing3
      run: |
        pwd
        ls -al
        cd /
        ls -al
        df -h
        cat /__w/_temp/*.sh
        echo a
